// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWkRM9PX2SXa19J3255-yhU29LtmeuAHw',
    appId: '1:18882107844:web:4254e2ca1322e45056ec91',
    messagingSenderId: '18882107844',
    projectId: 'soilanalyzerosiris',
    authDomain: 'soilanalyzerosiris.firebaseapp.com',
    storageBucket: 'soilanalyzerosiris.appspot.com',
    measurementId: 'G-HGZ1HLRQQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40lBk4pTT9KFCFPw40YMwfsJM1L5HhfA',
    appId: '1:18882107844:android:a356976ef29d258d56ec91',
    messagingSenderId: '18882107844',
    projectId: 'soilanalyzerosiris',
    storageBucket: 'soilanalyzerosiris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgj73U9R1AqgW_EZCjdpmSomXDVzEN3wo',
    appId: '1:18882107844:ios:7fb85739a59896a056ec91',
    messagingSenderId: '18882107844',
    projectId: 'soilanalyzerosiris',
    storageBucket: 'soilanalyzerosiris.appspot.com',
    iosClientId: '18882107844-65s7fjm6kd2ece2hc4e77j0d8198u9g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihosiris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgj73U9R1AqgW_EZCjdpmSomXDVzEN3wo',
    appId: '1:18882107844:ios:c9d66164add0675656ec91',
    messagingSenderId: '18882107844',
    projectId: 'soilanalyzerosiris',
    storageBucket: 'soilanalyzerosiris.appspot.com',
    iosClientId: '18882107844-f4urmngpdrq1e22cgg5v88tsnk566v2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.osiris2',
  );
}
